### ISSUE TITLE
C++03 WaitSet example should use handlers and WaitSet::dispatch()

### ISSUE THREAD

**Issue by titosanxez** [rticommunity/rticonnextdds-examples#152]

**Comment by epallares** [comment]
I have made a pull request with a C++11 example of the waitset_status_cond that uses handlers and dispatch().

**Comment by iblancasa** [comment]
You implemented that change as part of #157, right? @epallares

**Comment by epallares** [comment]
> You implemented that change as part of #157, right? @epallares

yes!
