### ISSUE TITLE
Homogeinize README file format across examples

### ISSUE THREAD

**Issue by jpovedano** [rticommunity/rticonnextdds-examples#167]
Right now, there is multiple formats for README files in the examples:
- TXT files: for "old" examples
- RST
- MD

I think there would be a common format for all the examples under this project.

At the very minimum, all the TXT examples, should be moved to MD/RST to have good integration with github

**Comment by iblancasa** [comment]
I totally agree. First, we need to decide what format we want to use.

Since we are using RST for other projects... RST could be the best option.

**Comment by titosanxez** [comment]
I agree with @iblancasa, let's go with RST.

**Comment by lulivi** [comment]
Finally @iblancasa and @fgaranda decided to go with Markdown for its easy-to-read and easy-to-write format.

**Comment by fgaranda** [comment]
We have decided the follow a standard README.md format for all examples. These have been updated as part of the migration to CMake and are now part of our `develop` branch. We can close this issue.
