### ISSUE TITLE
Problem connecting monitor library

### ISSUE THREAD

**Issue by Marconi666** [rticommunity/rticonnextdds-examples#171]
```bash
RTI Data Distribution Service EVAL License issued to no <email> For
 non-production use only.
Expires on 06-Oct-2018 See www.rti.com for more information.
DDS_DomainParticipantGlobals_initializeWorkerFactoryI:!Potential library mismatc
h.
This may happen if your application uses the static and the shared RTI core
libraries simultaneously.
For example, using the shared RTI Monitoring library
and linking statically with the RTI core libraries will cause this mismatch
RTIDefaultMonitorPublisher_create:!get worker factory
DDS_DomainParticipantGlobals_initializeWorkerFactoryI:!Potential library mismatc
h.
This may happen if your application uses the static and the shared RTI core
libraries simultaneously.
For example, using the shared RTI Monitoring library
and linking statically with the RTI core libraries will cause this mismatch
RTIDefaultMonitorPublisher_delete:!get worker factory
[CREATE Participant]DDS_DomainParticipantMonitoring_initializeMonitoringLibrary:
ERROR: Failed to get monitoring class
[CREATE Participant]DDS_DomainParticipantMonitoring_initializeI:!create monitori
ng library instance
[CREATE Participant]DDS_DomainParticipant_createI:!create builtin monitoring sup
port
[CREATE Participant]DDS_DomainParticipantFactory_create_participant_disabledI:!c
reate participant
DDSDomainParticipant_impl::create_disabledI:!create participant
DDSDomainParticipant_impl::createI:!create participant
DomainParticipantFactory_impl::create_participant():!create failure creating par
ticipant
create_participant error
```

**Comment by iblancasa** [comment]
@Marconi666, could you provide me with more information about your issue?

Another option is opening a post in https://community.rti.com/

**Comment by Marconi666** [comment]
@iblancasa thanks for your answer.... I want to monitor my data traffic through RTI-Monitor. This must enable the monitor library. This problem occurred when I configured monitor in my code.

**Comment by fgaranda** [comment]
Hi @Marconi666,

Have you been able to run the example or you are still facing this problem when loading the monitoring library?

On one hand, it looked like your evaluation license had expired, so Connext DDS was unable to create the DomainParticipant in your application, which is responsible for loading the monitoring library and creating the rest of entities. Have you tried with a new license file? Do you need to renew your evaluation license?

Once you have a working license file, you can enable the Monitoring library as explained [here](https://community.rti.com/static/documentation/connext-dds/5.2.0/doc/manuals/connext_dds/html_files/RTI_ConnextDDS_CoreLibraries_UsersManual/Content/UsersManual/Method_1_Change_the_Participant_QoS_to_A.htm#rti_monitoring_library_usage_2783583765_1066202).

**Comment by fgaranda** [comment]
@Marconi666, just for reference, here's documentation on how to configure Connext to pick up your license file: https://community.rti.com/static/documentation/connext-dds/6.0.0/doc/manuals/connext_dds/html_files/RTI_ConnextDDS_CoreLibraries_GettingStarted/index.htm#GettingStarted/License_Management.htm

Note that to enable the Monitoring library you will need to follow the instructions described here:
https://community.rti.com/static/documentation/connext-dds/6.0.0/doc/manuals/connext_dds/html_files/RTI_ConnextDDS_CoreLibraries_UsersManual/index.htm#UsersManual/Method_1_Change_the_Participant_QoS_to_A.htm
