### ISSUE TITLE
Avoid the use of the full path when linking dynamically

### ISSUE THREAD

**Issue by iblancasa** [rticommunity/rticonnextdds-examples#223]
### Information

- **RTI Product**: ConnextDDS
- **Version**: 6.0.0 and lower
- **Operating system**: Linux and Darwin were confirmed
- **Compiler**: gcc and clang
- **Compiler version**: all
- **Additional information**: this problem affects to all the operating systems where the `CMAKE_PLATFORM_USES_PATH_WHEN_NO_SONAME` CMake variable is equal to 1.

### What is the current behavior?
In CMake, when we link against an imported target, CMake will try to get the soname of the library if `CMAKE_PLATFORM_USES_PATH_WHEN_NO_SONAME` is equal to 1 and will link against the library using `-llibraryname`. If the library has not a soname, CMake will use the complete path to the library in order to link against it. ConnextDDS libraries are not defining a soname and, for that reason, CMake is adding the complete path to the library. One example:

```bash
/usr/local/bin/cmake -E cmake_link_script CMakeFiles/CameraImage_publisher.dir/link.txt --verbose=1
/usr/bin/c++  -O3 -DNDEBUG   CMakeFiles/CameraImage_publisher.dir/CameraImage_publisher.cxx.o CMakeFiles/CameraImage_publisher.dir/CameraImage.cxx.o CMakeFiles/CameraImage_publisher.dir/CameraImagePlugin.cxx.o  -o CameraImage_publisher  -L/home/israel/rti_connext_dds-6.0.0/lib/x64Linux4gcc7.3.0 -Wl,-rpath,/home/israel/rti_connext_dds-6.0.0/lib/x64Linux4gcc7.3.0 /home/israel/rti_connext_dds-6.0.0/lib/x64Linux4gcc7.3.0/libnddscpp2.so /home/israel/rti_connext_dds-6.0.0/lib/x64Linux4gcc7.3.0/libddsmetp.so /home/israel/rti_connext_dds-6.0.0/lib/x64Linux4gcc7.3.0/libnddsc.so /home/israel/rti_connext_dds-6.0.0/lib/x64Linux4gcc7.3.0/libnddscore.so -ldl -lnsl -lm -lpthread -lrt
```
This can cause some issues when there are libraries that depends on other libraries that are part of the link step. For instance, `libnddscpp2.so` has a dependency with `libnddsc.so`. The linker will be able to link the executable but it will not be able to detect that the library `libnddsc.so` used to link the executable is the same library needed by `libnddscpp2.so` and this can make not work the use of `rpath`.

### Steps to reproduce the issue
* CMake 3.12
* Dynamic linking
* One platform where `CMAKE_PLATFORM_USES_PATH_WHEN_NO_SONAME=1`

### What is the expected behavior?
Link using the `-lnddscore` format instead the full path to the library.

### Suggested solutions
We just need to disable the use of soname in the imported targets.

**Comment by lulivi** [comment]
Should we close this issue as it is fixed?

**Comment by iblancasa** [comment]
@lulivi yes :)
