### ISSUE TITLE
Compilation issue on Recording Service example 

### ISSUE THREAD

**Issue by Antoniolm** [rticommunity/rticonnextdds-examples#240]
The Service Admin example of Recording Service throws a compilation error due to how we include dds/core in the example. I could reproduce the issue on x64Linux4gcc7.3.0 and x64Linux3gcc5.3.0

**Comment by iblancasa** [comment]
@ManuelJNunez, can you take a look to this issue?

**Comment by ManuelJNunez** [comment]
This compilation actually works, maybe this issue is fixed and should be closed.

**Comment by lulivi** [comment]
@ManuelJNunez which architecture did yo use to reproduce the issue?

**Comment by ManuelJNunez** [comment]
@lulivi x64Linux4gcc7.3.0
