### ISSUE TITLE
Update IDL declarations to IDL 4. / XTYPES 1.3 syntax

### ISSUE THREAD

**Issue by GerardoPardo** [rticommunity/rticonnextdds-examples#250]
This change impacts only the IDL files. It should have no impact on the code. 
IDL 4 / XTTYPES added a better notation for annotations. It also added new names for the primitive integer types that are less ambiguous.   To promote this best practice the examples should be updated to use this new syntax. Specifically:

(1) Annotations:  Use  the @annotationName prefix rather than the //@annotationName suffix. For example. Write this:
```
struct keys {
    @key long code; 
};
```
Instead of this:
```
struct keys {
    long code; //@key
 };
```

(2) Integers. Use the new notation.
For example. Write this:
```
struct age {
    int32 code; 
 };
```
Instead of this:
```
struct keys {
    long code; 
 };
```

**Comment by fgaranda** [comment]
The fix has been merged in develop. It'll be merged to master along with all the tasks we are completing this month.
