### ISSUE TITLE
Use GitHub templates for PRs, issues...

### ISSUE THREAD

**Issue by lulivi** [rticommunity/rticonnextdds-examples#256]
It would be interesting to make use of [Github Builtin Issues and Pull-requests templates](https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository#creating-issue-templates) and [Contributing guidelines](https://help.github.com/en/github/building-a-strong-community/setting-guidelines-for-repository-contributors) as well as modernize the [Wiki](https://github.com/rticommunity/rticonnextdds-examples/wiki) with new content and entries.

**Comment by iblancasa** [comment]
Oh, it seems they changed the way to do this... we have the templates under the `.github/ISSUE_TEMPLATE` folder

**Comment by lulivi** [comment]
Yes, there is a new way, but we can use the templates under `.github` folder.

**Comment by iblancasa** [comment]
Useful repository: https://github.com/stevemao/github-issue-templates

**Comment by iblancasa** [comment]
@ManuelJNunez, can you take care of this issue? Thanks!

**Comment by ManuelJNunez** [comment]
This repository already contains PR and Issues templates under `.github` folder.

**Comment by iblancasa** [comment]
Yes, but we can improve the [contributing.md](https://github.com/rticommunity/rticonnextdds-examples/blob/master/CONTRIBUTING.md) file to include things like "how to run tests", "how to submit a change" or similar things (as explained in the links shared by @lulivi)

**Comment by ManuelJNunez** [comment]
We also could change the PULL_REQUEST_TEMPLATE to something like that:

```Markdown
### Summary


### Details and comments


### Checks
- [ ] I have updated the documentation accordingly.
- [ ] I have read the CONTRIBUTING document.
```

**Comment by ManuelJNunez** [comment]
Why don't we delete `ISSUE_TEMPLATE.md` so that we can use the issue templates in `.github/ISSUE_TEMPLATE`?

**Comment by iblancasa** [comment]
@ManuelJNunez  ok, go ahead.

**Comment by lulivi** [comment]
totally makes sense

**Comment by lulivi** [comment]
Already done.
