### ISSUE TITLE
connext dds blocking 

### ISSUE THREAD

**Issue by Francisobiagwu** [rticommunity/rticonnextdds-examples#266]
### Information

- **RTI Product: python examples**:
- **Version: n/a**:
- **Operating system: ubuntu 19**:
- **Compiler: n/a**:
- **Compiler version: n/a **:
- **Additional information**:

### What is the current behavior?
Each time I modify the reader.py and writer.py example script. Let say, there is an error, maybe in the xml file or in the code, it seems like a kind of blocking mechanism is activated. When I run the reader.py the reader won't be able to read the data. Even when I fix the error by reverting the code to the original form, the reader won't work until I restart my computer. Please is there any explanation for this?

### Steps to reproduce the issue
modify the xml file to give an error, and then run the reader.py

### What is the expected behavior?
the reader.py doesn't read data on the bus

### Suggested solutions
Not sure, but I would want to confirm if there is any blocking mechanism, and what is the duration of the block?
![dds_error](https://user-images.githubusercontent.com/19335305/69162074-17571800-0aba-11ea-9ef3-ee9360526b08.png)

**Comment by fgaranda** [comment]
Hi @Francisobiagwu,

Could you file #266 and #267 in the [RTI Connector for Python repository](https://github.com/rticommunity/rticonnextdds-connector-py/issues)? This repository includes focuses on examples that run with native RTI Connext and does not cover the simplify Python API of Connector.

Thanks!
Fernando
