### ISSUE TITLE
How to subscribe to multiple messages on different domain

### ISSUE THREAD

**Issue by Francisobiagwu** [rticommunity/rticonnextdds-examples#267]
From the python example template, I created a new domain and then I attempted to have a participant subscribe to data from two different domains. But it seemed like I cannot use the same domain_participant name twice. Please, do I change this xml to make this possible?

    
    <domain_library name="MyDomainLibrary">
        <domain name="CameraDomain" domain_id="0">
            <register_type name="Camera" kind="dynamicData" type_ref="Camera"/>
            <topic name="CameraData" register_type_ref="Camera"/>
        </domain>

        <domain name="LidarDomain" domain_id="1">
            <register_type name="Lidar" kind="dynamicData" type_ref="Lidar"/>
            <topic name="LidarData" register_type_ref="Lidar"/>
        </domain>
    </domain_library>

    <participant_library name="MyParticipantLibrary">

        <domain_participant name="Console" domain_ref="MyDomainLibrary::CameraDomain">
            <subscriber name="CameraDataSubscriber">
                <data_reader name="CameraDataReader" topic_ref="CameraData"/>
            </subscriber>

        </domain_participant>

        <domain_participant name="Console" domain_ref="MyDomainLibrary::LidarDomain">
            <subscriber name="LidarDataSubscriber">
                <data_reader name="LidarDataReader" topic_ref="LidarData"/>
            </subscriber>
        </domain_participant>

    </participant_library>

**Comment by fgaranda** [comment]
Hi Francisobiagwu,

Could you file #266 and #267 in the [RTI Connector for Python repository](https://github.com/rticommunity/rticonnextdds-connector-py/issues)? This repository includes focuses on examples that run with native RTI Connext and does not cover the simplify Python API of Connector.

Thanks!
Fernando
