### ISSUE TITLE
Support of DDS-XTypes 1.2 version

### ISSUE THREAD

**Issue by rnareddy646** [rticommunity/rticonnextdds-examples#273]
Hello,

I would like to ask if the RTI Connext implementation supports any of the
Extensible and Dynamic Topic Types for DDS as seen in the
https://www.omg.org/spec/DDS-XTypes/1.2

Please help us on this , we are trying to check interoperability test between different vendors to see if this supports.
Thanks 
Sudharsan

**Comment by fgaranda** [comment]
Hello Sudharsan,

RTI Connext DDS includes partial support for the "Extensible and Dynamic Topic Types for DDS" (DDS-XTypes) specification1 from the Object Management Group (OMG), version 1.2.

If you want to learn more about the type safety and type evolution, type system, data representation, and type representation features implemented in RTI Connext DDS, please check out the Getting Started Guide Addendum for Extensible Types available in [HTML](https://community.rti.com/static/documentation/connext-dds/6.0.0/doc/manuals/connext_dds/getting_started_extras/html_files/RTI_ConnextDDS_CoreLibraries_GettingStarted_ExtensibleAddendum/index.htm) and [PDF](https://community.rti.com/static/documentation/connext-dds/6.0.0/doc/manuals/connext_dds/getting_started_extras/RTI_ConnextDDS_CoreLibraries_GettingStarted_ExtensibleTypesAddendum.pdf) format.

Let us know if you have any specific questions.
