### ISSUE TITLE
Prevent polling subscriber from exiting if no data is read

### ISSUE THREAD

**Issue by rgrti** [rticommunity/rticonnextdds-examples#280]
### Information

- **RTI Product**: polling example code
- **Version**: currently published code on rti.com and github
- **Operating system**: all
- **Compiler**: all
- **Compiler version**: all
- **Additional information**: the c++ and c examples are affected
https://github.com/rticommunity/rticonnextdds-examples/blob/master/examples/connext_dds/polling_read/c/poll_subscriber.c
and
https://github.com/rticommunity/rticonnextdds-examples/blob/master/examples/connext_dds/polling_read/c%2B%2B/poll_subscriber.cxx
see: https://jira.rti.com/browse/COMMUNITY-11

### What is the current behavior?
If discovery isn't completed, the subscriber side polling obviously fails to read data. But when it fails the program completely exits instead of sleeping and attempting to poll again in the future (like other code examples do). 

### Steps to reproduce the issue
start the subscriber first or move the sleep to the end of the main loop of the subscriber

### What is the expected behavior?
the subscriber process will not error out and exit completely, it should simply print an error that no data could be polled, go to sleep, and try polling again next time. 

### Suggested solutions
change the 'break' to a 'continue'
more information, issue #3: https://jira.rti.com/browse/COMMUNITY-11

**Comment by fgaranda** [comment]
Resolved with #281.
