### ISSUE TITLE
Add github action

### ISSUE THREAD

**Issue by jwillemsen** [rticommunity/rticonnextdds-examples#291]
### Information

- **RTI Product**: RTI Connext DDS 
- **Version**: Any

### Suggested solutions

Currently travis-ci is used by this project, would love to see also usage of github checks, which is used more and more and has less limitations than travis

**Comment by jwillemsen** [comment]
Related to #290

**Comment by lulivi** [comment]
You are talking about GitHub Actions, right?

**Comment by jwillemsen** [comment]
Yes

**Comment by lulivi** [comment]
Now using GitHub Actions to build the pr! Closing this...
