### ISSUE TITLE
Update the README.md of RS constrained WAN example with the GitHub link 

### ISSUE THREAD

**Issue by angelrti** [rticommunity/rticonnextdds-examples#297]
The example on the RTI community site does not exist yet, because hosting the xml files on github is a prerequisite. 

I will update the readme.md when the example exists, and include the link

_Originally posted by @rgrti in https://github.com/rticommunity/rticonnextdds-examples/pull/296_

**Comment by rgrti** [comment]
I matched the title of the community example so it matches the link in the README.md, no changes are needed

**Comment by rgrti** [comment]
The community example is now public. You can verify the link in this [readme](https://github.com/rticommunity/rticonnextdds-examples/blob/constrained-wan-example/examples/routing_service/routing_service_constrained_wan/README.md) correctly links to the [community example](https://community.rti.com/examples/Routing-Service-Constrained-WAN-Example)

**Comment by angelrti** [comment]
No changes needed, rgrti modified the readme to point to an example in our community and we don't need to add anything to the readme.
