### ISSUE TITLE
Update versions listed in README.md

### ISSUE THREAD

**Issue by samuelraeburn** [rticommunity/rticonnextdds-examples#330]
(Not following template since it is largely irrelevant to what I am reporting)

The current README.md, in the develop branch states:

> The examples contained in the master and develop branches of this repository have been built and tested against RTI Connext DDS 6.0.0. If you need examples that have been built and tested against older versions of RTI Connext DDS, please check out the appropriate branch:
    release/5.3.0
    release/5.2.0
    release/5.1.0
    release/5.0.0

This is no longer true, with the latest examples added by Antonio (qos logging, instance statistics, fragmentation statistics, etc.) only working with 6.1.0. We should update the README.md. Additionally, maybe a new release branch needs to be created for 6.0.0.

**Comment by iblancasa** [comment]
@ManuelJNunez can you take care of this issue?

**Comment by ManuelJNunez** [comment]
Currently, the README.md of the develop branch is up to date:

>The examples contained in the master and develop branches of this repository have been built and tested against RTI Connext DDS 6.1.0. If you need examples that have been built and tested against older versions of RTI Connext DDS, please check out the appropriate branch:
release/6.0.0
release/5.3.0
release/5.2.0
release/5.1.0
release/5.0.0

**Comment by iblancasa** [comment]
@ManuelJNunez perfect! Thanks!

I'll close this issue since it seems everything is OK 🥳
