### ISSUE TITLE
Unify the minimum required CMake version across all the examples

### ISSUE THREAD

**Issue by iblancasa** [rticommunity/rticonnextdds-examples#342]
### Information
All the examples should use the same minimum required version for CMake.

### What is the current behavior?
Some of them uses CMake 3.11 and others 3.7.

**Comment by iblancasa** [comment]
@ManuelJNunez can you take care of this issue?

**Comment by ManuelJNunez** [comment]
The minimum required CMake version is the same across all the example, so I think this issue could be closed.
