### ISSUE TITLE
Take care of the new version for Travis-CI builds

### ISSUE THREAD

**Issue by lulivi** [rticommunity/rticonnextdds-examples#347]
### Information

- **RTI Product**: RTIConnextDDS
- **Version**: 6.0.0/6.1.0
- **Operating system**: --
- **Compiler**: --
- **Compiler version**: --
- **Additional information**:

### What is the current behavior?

Travis builds are failing in *develop* because there are examples for the next release of ConnextDDS.

### Suggested solutions

We could add a check for the new examples to avoid building them until we have the new version installation for Travis-CI or something similar.

**Comment by lulivi** [comment]
@iblancasa @fgaranda What do you think will be the best approach?

One possible approach is to check the version in the examples/connext_dds/CMakeLists.txt for the new examples.

**Comment by iblancasa** [comment]
Yes, I think that is the best idea.

**Comment by iblancasa** [comment]
@ManuelJNunez, can you take a look to this issue?
