### ISSUE TITLE
Apply format and code conventions to java source files

### ISSUE THREAD

**Issue by ManuelJNunez** [rticommunity/rticonnextdds-examples#398]
## Enhacement description

To ensure the best practices in `Java` code it would be convenient to use a tool that allows us to format the source code and check if a file (or files) is following the style/format rules. In addition, it would be necessary to create a new workflow to check the code in each push or pull request.

**Comment by ManuelJNunez** [comment]
Already closed on develop. When merging to master it will be closed automatically.

**Comment by lulivi** [comment]
This should have been closed when merging to master :thinking: (#399)
