### ISSUE TITLE
Add a macro in CMake to automatically discover 'language' folders and add them

### ISSUE THREAD

**Issue by angelrti** [rticommunity/rticonnextdds-examples#407]
### Information

- **RTI Product**: N/A
- **Version**: N/A
- **Operating system**: N/A
- **Compiler**: N/A
- **Compiler version**: N/A
- **Additional information**: This happens in the connext_dds/CMakeLists.txt

### What is the current behavior?
Currently, in the connext_dds/CMakeLists.txt we have to add examples manually for every language.

### Suggested solutions
We can have a macro that checks whether they exist and add those that exist. In that sense, we can have a macro that retrieves a name of the example to add, for example: `add_example("name_of_example")`

**Comment by ManuelJNunez** [comment]
This is a good idea!

**Comment by lulivi** [comment]
This was solved when mergin #393
