### ISSUE TITLE
[ENH] In a PR build the example with the merge of the original branch into the destination.

### ISSUE THREAD

**Issue by softwarejimenez** [rticommunity/rticonnextdds-examples#462]
### Enhancement description

In a PR build the example with the merge of the original branch into the destination.

The reason for the idea is because if there is something fixed in the destination branch but failing in the original branch. The build will fail and it will not be possible to do the merge.

For example in the PR: https://github.com/rticommunity/rticonnextdds-examples/pull/458

**Comment by ManuelJNunez** [comment]
This is how Jenkins is configured at the moment.
