### ISSUE TITLE
[BUG] Missing CMakeLists.txt file in rticonnextdds-examples\examples\connext_dds\flat_data_latency\c++11

### ISSUE THREAD

**Issue by howard-rti** [rticommunity/rticonnextdds-examples#466]
Subject says it all...

### System information

- **RTI Product**:
- **Version**:
- **Operating system**:
- **Compiler**:
- **Compiler version**:
- **Additional information**:

**Comment by lulivi** [comment]
Fixed in ee1c50050b8c7fb216d51c925f2a539126477f17
